<?php
$user_id ='';
$emp_id='';
$massage=''; 
$firstname='';
$lastname='';
$emailid='';
$mobileno='';
$photo='';
$gender=''; 
$high_school='';
$intermediate_school='';
$diploma='';
$graduate='';
$masters='';
$servername='localhost';
$username='root';
$password='manas98077raj';
$dbname='prologictechnologies';
$GLOBALS["poly"]="";
$GLOBALS["btech"]="";
$GLOBALS["mtech"]="";
$GLOBALS["mba"]="";
?>