<?php
$user_id ='';
$update_id='';
$emp_id='';
$massage=''; 
$fatch_firstname='';
$fatch_lastname='';
$fatch_emailid='';
$fatch_mobileno='';
$fatch_photo='download.jfif';
$fatch_gender=''; 
$fatch_high_school='';
$fatch_intermediate_school='';
$fatch_diploma='';
$fatch_graduate='';
$fatch_masters='';
$GLOBALS["poly"]="";
$GLOBALS["btech"]="";
$GLOBALS["mtech"]="";
$GLOBALS["mba"]="";
?>